version: '3.8'
services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
  create-tables:
    build:
      context: .
      dockerfile: Dockerfile
      target: create-tables
    depends_on:
      - dynamodb-local
    restart: "no"
  webhook-receiver:
    build:
      context: .
      dockerfile: Dockerfile
      target: webhook-receiver
    image: webhook-receiver
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - dynamodb-local
  hinatazaka-blog-notifier:
    build:
      context: .
      dockerfile: Dockerfile
      target: hinatazaka-blog-notifier
    image: hinatazaka-blog-notifier
    env_file:
      - .env
    depends_on:
      - dynamodb-local
