name: Test Coverage

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ">=1.18"

    - name: Download dependencies
      run: go mod download

    - name: Test Coverage
      run: |
        go test -coverprofile=coverage.out ./...

    - name: Report Coverage
      uses: k1LoW/octocov-action@v0
